# Generated by Django 4.2.5 on 2024-03-02 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="booking.user",
                    ),
                ),
                ("fathers_name", models.CharField(default="", max_length=30)),
                ("mothers_name", models.CharField(default="", max_length=30)),
                ("phone", models.CharField(default="", max_length=10)),
                ("email", models.CharField(default="", max_length=30)),
                ("address", models.CharField(default="", max_length=50)),
            ],
        ),
    ]
