# Generated by Django 4.2.5 on 2024-03-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="from_to",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_from", models.CharField(max_length=30)),
                ("book_to", models.CharField(max_length=30)),
                ("date", models.DateField()),
                ("car", models.CharField(max_length=30)),
            ],
        ),
    ]
